### ISSUE TITLE
Prefill jobId and vehicleId field with last used value

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper-navigation-example-legacy#14]
I had a brief look and this doesn't seem to be that easy. Maybe we have to use an activity instead of a Dialog?

**Comment by devemux86** [comment]
If I understand correctly the issue, could store the last used values in static variables which would be available until the Android `onDestroy` is called.

**Comment by boldtrn** [comment]
Thanks for the feedback @devemux86. The issues for me was how to prefill the text boxes with the last used values. I couldn't find a good way to do this for a Dialog, things seem different for an Activity?

But maybe I was doing something wrong :)?

**Comment by devemux86** [comment]
If store the last used values in static variables which live across Android app lifecycle, then can retrieve them on each dialog (or other component) initialization and prefill the text boxes. Is that the requirement?

**Comment by boldtrn** [comment]
Yes. But I haven't found a way to properly do this in the limited available time, so I decided to check this in a separate issue :).

**Comment by boldtrn** [comment]
This was fixed in #25.
