### ISSUE TITLE
Investigate Issue with the next turn label

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper-navigation-example-legacy#16]
When navigating [this route](https://graphhopper.com/maps/?point=51.428936%2C14.22788&point=51.426484%2C14.228765), the next turn label shows the turn after the next one instead. We should check why this happens.

See the attached image, where the turn after the current one is the second next turn.

**Comment by karussell** [comment]
This seems to be a general bug also for continue etc and always for the second instruction

**Comment by boldtrn** [comment]
This seems to be a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/1228 and will be fixed in https://github.com/mapbox/mapbox-navigation-android/pull/1408
