### ISSUE TITLE
"Unknowledged" user get "current route is not available" or "location not found"

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-navigation-example-legacy#35]
We should either postpone results of search results and display them as soon as the current location is available or explain in more detail what needs to be done (wait until current location is shown)

**Comment by boldtrn** [comment]
You are not talking about geocoding search but route planning, correct?

We could create a pop-up dialog that explains what needs to be done.

Do you think it should be an initial dialog at first start that explains the app? We could also think about adding a `?` to the bar at the top that shows some basic instructions?

**Comment by karussell** [comment]
> Do you think it should be an initial dialog at first start that explains the app?

Yes, something where we say 
1. "no warranty for navigation + be careful and follow signs" and 
2. "wait until your location is displayed on the map, then search the destination. Now tap on the text window and finally click the navigate icon"

Or something like this. Obviously a more intuitive UI would mean to invest lots of time into it and such a dialog would be much easier to implement and improve the usage&understanding.

**Comment by devemux86** [comment]
Is there possibility from the framework to have location without GPS (e.g. WiFi) ?

Last time testing the app, it was impossible because inside cannot have GPS. :slightly_smiling_face:

**Comment by boldtrn** [comment]
I think the location provider internally uses the `android.location.LocationManager.GPS_PROVIDER` and not the `FUSED_PROVIDER`. I don't know why, but it's pretty deep in one of the dependencies, so it's not easy to change :(.

I think it is possible to use the Google Location Engine, but I think it's required to add play services to the APK and then the APK would only work on devices with Google Play services installed?

**Comment by devemux86** [comment]
That's why many still prefer the Android platform low-level [location API](https://developer.android.com/guide/topics/location/strategies). :slightly_smiling_face:
