### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by juergengunz** [graphhopper/graphhopper-navigation-example-legacy#38]
Is there an iOS version available already?

**Comment by karussell** [comment]
No. An iOS version is also not planned. We need to find out if the demand is big enough to justify the spent resources.

**Comment by boldtrn** [comment]
Just to clarify, we currently don't maintain a fork of [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios).

If you are wondering why we had to fork, have a look [here](https://www.graphhopper.com/blog/2019/02/05/building-a-navigation-app-using-open-source-tools/).

This means that we officially don't provide support for iOS. But, it should be possible nevertheless.

In [this commit](https://github.com/mapbox/mapbox-navigation-ios/commit/faf2e4ae94d052380853d9615181d139115a9747#diff-60bb710c5144ead8f8cb73a22de579ab), Mapbox introduced a closed source nav native library, that is licensed under a restricted license that doesn't allow the usage with GraphHopper, so we recommend to pick the version before this, which should be [v0.21.0](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v0.21.0).

If you want to try it, please let us know if you were successful or if there are any issues. If adjustments to our response format are needed, please let us know [here](https://github.com/graphhopper/graphhopper-navigation).

**Comment by karussell** [comment]
Thanks for your clarification @boldtrn !

**Comment by car0210** [comment]
Hi! Any news regarding graphhopper navigation iOS?
