### ISSUE TITLE
To what do you refer with "No dependency to MapBox"

### ISSUE THREAD

**Issue by lasd14** [graphhopper/graphhopper-navigation-example-legacy#51]
Hi, you have an amazing implementation of a turn by turn Navigation, but I´m a little big confused because you say in the repository benefits it says that "no dependency to Mapbox i.e. no Mapbox contract required. The Mapbox key can be a random string". 

I´m so surprised when I read that because I want to know how you achieve this, I know that is an oper source project but if someone explain me how to consume the MapBox Navigation SDK without pay nothing, I´ll be very greatful.

**Comment by karussell** [comment]
You'll have to set up the server-side (your own routing server). You can do this via e.g. the open source graphhopper routing engine or others.

Please also have a look into: https://github.com/maplibre/maplibre-navigation-android which is a more recent fork (from a different company)

**Comment by lasd14** [comment]
Thanks for your answer, I'll take a look
