### ISSUE TITLE
Issue with Mapilion API Key and style urls

### ISSUE THREAD

**Issue by aynalemL** [graphhopper/graphhopper-navigation-example-legacy#54]
I have encountered an issue with obtaining an API key directly from Mapilion for accessing their services. It appears that Mapilion provides the API key through RapidAPI. Consequently, the map_view_styleUrl provided via RapidAPI looks like this: https://mapilion-vector-and-raster-map-tiles.p.rapidapi.com/rapid-api/stylejson/osm-bright?key=[MAP_API_KEY]. However, when I directly put this URL in the developer-config.xml file, it does not work.  It seems that Mapilion expects the API key to be sent in the request header rather than as a URL parameter.

The original code in the GitHub repository had the style URL as: https://tiles.mapilion.com/assets/osm-bright/style.json?key=[MAP_API_KEY].

Has anyone successfully used the RapidAPI version? I have attempted to bring up the sample demo on an Android device, but it only displays a blank page with header buttons and no map. I suspect this issue is related to the styles not being downloaded properly.

**Comment by boldtrn** [comment]
Instead of passing the parameter key, you can pass the parameter `rapidapi_key`, so for example: https://mapilion-vector-and-raster-map-tiles.p.rapidapi.com/rapid-api/stylejson/osm-bright?rapidapi-key=[YOUR_KEY].

Let me know if this fixes this issue for you.

**Comment by aynalemL** [comment]
@boldtrn thank you so much. That fixed the issue for me.
